{% set version = "0.5.0" %}

package:
  name: graphviz2drawio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/g/graphviz2drawio/graphviz2drawio-{{ version }}.tar.gz
    sha256: 0bc8c1fec4b8e22e96f6991f44eba95250242aa9c748057d6f5d114bd90f3809
  - folder: src
    url: https://github.com/hbmartin/graphviz2drawio/archive/v{{ version }}.tar.gz
    sha256: 744c13ad5b1bd3300b41966ba837381a49463aa8d77d5d9a52664cb4bc6e56a2

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - graphviz2drawio=graphviz2drawio.__main__:main

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - puremagic
    - pygraphviz
    - python >=3.10
    - svg.path

test:
  source_files:
    - src/test
  imports:
    - graphviz2drawio
    - graphviz2drawio.graphviz2drawio
  commands:
    # TODO: fails on old puremagic dep, remove after https://github.com/conda-forge/puremagic-feedstock/pull/5
    {% if version != "0.4.0" %}
    - pip check
    {% endif %}
    - graphviz2drawio --version | grep -iE "{{ version.replace('.', '\.') }}"
    - graphviz2drawio --help
    - graphviz2drawio src/test/directed/hello.gv.txt
    - cd src && coverage run --source=graphviz2drawio --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=81
  requires:
    - pip
    - pytest
    - coverage
    - m2-grep  # [win]

about:
  home: https://github.com/hbmartin/graphviz2drawio
  summary: Convert graphviz (dot) files into draw.io (mxGraph) format
  dev_url: https://github.com/hbmartin/graphviz2drawio
  license: GPL-3.0-or-later
  license_file: dist/LICENSE.md
  doc_url: https://graphviz2drawio.readthedocs.io
  doc_source_url: https://github.com/hbmartin/graphviz2drawio/tree/v{{ version }}/doc/source

extra:
  recipe-maintainers:
    - bollwyvl
