{% set python_min = '3.10' %}
{% set version = "1.0.0" %}

package:
  name: graphviz2drawio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/g/graphviz2drawio/graphviz2drawio-{{ version }}.tar.gz
    sha256: 5409f11cd080b28d77408817559b6481250b3053cec757ab933b92b3075606a5
  - folder: src
    url: https://github.com/hbmartin/graphviz2drawio/archive/v{{ version }}.tar.gz
    sha256: ca19786c3a43ac51d81f870ce55950305d690fe2c2c3b1fc593310d48a17c948

build:
  number: 1
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - graphviz2drawio=graphviz2drawio.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - puremagic
    - pygraphviz
    - python >={{ python_min }}
    - svg.path

test:
  source_files:
    - src/test
  imports:
    - graphviz2drawio
    - graphviz2drawio.graphviz2drawio
  commands:
    - pip check
    - graphviz2drawio --version | grep -iE "{{ version.replace('.', '\.') }}"
    - graphviz2drawio --help
    - graphviz2drawio src/test/directed/hello.gv.txt
    - cd src && coverage run --source=graphviz2drawio --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=73
  requires:
    - pip
    - pytest
    - coverage
    - m2-grep  # [win]
    - python {{ python_min }}

about:
  home: https://github.com/hbmartin/graphviz2drawio
  summary: Convert graphviz (dot) files into draw.io (mxGraph) format
  dev_url: https://github.com/hbmartin/graphviz2drawio
  license: GPL-3.0-or-later
  license_file: dist/LICENSE.md
  doc_url: https://graphviz2drawio.readthedocs.io
  doc_source_url: https://github.com/hbmartin/graphviz2drawio/tree/v{{ version }}/doc/source

extra:
  recipe-maintainers:
    - bollwyvl
